version: '3'

services:

  # Mqtt broker service
  # docker compose run --service-ports mosquitto
  mqttbroker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      # - 9001:9001
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf


  # Video stream service
  vstream:
    image: bluenviron/mediamtx
    ports:
      - 8554:8554
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 8890:8890/udp
      - 8189:8189/udp
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.x.x


  # Panduza platform service
  platformpy:
    # image: ghcr.io/panduza/panduza-py-platform:latest
    # To use your local platform build
    image: local/panduza-py-platform
    privileged: true
    depends_on:
      - vstream
      - mqttbroker
    network_mode: host
    volumes:
      - .:/etc/panduza
      - /run/udev:/run/udev:ro

